### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by SorraTheOrc** [keijiro/ProceduralMotionTrack#3]
It would make reuse of this (and other Unity assets of similar style) much simpler if you could make this available under a recognized open source license. Any chance of that happening?

As things stand we simply cannot reuse this as the FAQ states "The assets may not be resold." which is a restriction on use thus preventing this code from being reused in an open source solution such as my own.

**Comment by keijiro** [comment]
Does UCL (Unity Companion License) work for you?

https://unity3d.com/legal/licenses/Unity_Companion_License

This is the default license for Unity packages/examples/tutorials/etc.

At the time I created this repository, UCL didn't exist, so I used the FAQ section to explain the situation. Now I think UCL would be a better option.

**Comment by keijiro** [comment]
Changed the license to UCL.

I'm closing the issue now. Please feel free to reopen for further questions.
